// Auto-generated by scripts/fetch-premium-emoji.mjs
// Last updated: 2026-04-05T09:41:58.061Z
// Total: 228 emoji

export interface PremiumEmojiEntry {
  id: string;
  fallback: string;
  label: string;
  tags: string[];
  set: string;
}

export const PREMIUM_EMOJI_DATA: PremiumEmojiEntry[] = [
  {
    "id": "5434144690511290129",
    "fallback": "📰",
    "label": "📰",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5312536423851630001",
    "fallback": "💡",
    "label": "Идея",
    "tags": [
      "idea",
      "light bulb",
      "идея",
      "лампочка"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5312016608254762256",
    "fallback": "⚡️",
    "label": "⚡️",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5377544228505134960",
    "fallback": "🎙",
    "label": "🎙",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5418085807791545980",
    "fallback": "🔝",
    "label": "🔝",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5370870893004203704",
    "fallback": "🗣",
    "label": "🗣",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5420216386448270341",
    "fallback": "🆒",
    "label": "🆒",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5379748062124056162",
    "fallback": "❗️",
    "label": "❗️",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5373251851074415873",
    "fallback": "📝",
    "label": "📝",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5433614043006903194",
    "fallback": "📆",
    "label": "📆",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5357315181649076022",
    "fallback": "📁",
    "label": "📁",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5309965701241379366",
    "fallback": "🔎",
    "label": "🔎",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5309984423003823246",
    "fallback": "📣",
    "label": "Мегафон",
    "tags": [
      "megaphone",
      "announce",
      "мегафон",
      "анонс"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5312241539987020022",
    "fallback": "🔥",
    "label": "Огонь",
    "tags": [
      "fire",
      "flame",
      "hot",
      "огонь",
      "пламя"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5312138559556164615",
    "fallback": "❤️",
    "label": "Красное сердце",
    "tags": [
      "heart",
      "love",
      "red",
      "сердце",
      "любовь"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5377316857231450742",
    "fallback": "❓",
    "label": "Вопрос",
    "tags": [
      "question",
      "вопрос"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5350305691942788490",
    "fallback": "📈",
    "label": "Рост",
    "tags": [
      "chart up",
      "growth",
      "рост"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5350713563512052787",
    "fallback": "📉",
    "label": "Падение",
    "tags": [
      "chart down",
      "decline",
      "падение"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5309958691854754293",
    "fallback": "💎",
    "label": "Алмаз",
    "tags": [
      "diamond",
      "gem",
      "алмаз",
      "бриллиант"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5350452584119279096",
    "fallback": "💰",
    "label": "Деньги",
    "tags": [
      "money",
      "cash",
      "деньги"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5309929258443874898",
    "fallback": "💸",
    "label": "💸",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5377690785674175481",
    "fallback": "🪙",
    "label": "🪙",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5310107765874632305",
    "fallback": "💱",
    "label": "💱",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5377438129928020693",
    "fallback": "⁉️",
    "label": "⁉️",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5309950797704865693",
    "fallback": "🎮",
    "label": "Игры",
    "tags": [
      "game",
      "gaming",
      "игры",
      "геймплей"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5350554349074391003",
    "fallback": "💻",
    "label": "Ноутбук",
    "tags": [
      "laptop",
      "computer",
      "ноутбук",
      "компьютер"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5409357944619802453",
    "fallback": "📱",
    "label": "Телефон",
    "tags": [
      "phone",
      "mobile",
      "телефон"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5312322066328853156",
    "fallback": "🚗",
    "label": "Машина",
    "tags": [
      "car",
      "машина"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5312486108309757006",
    "fallback": "🏠",
    "label": "Дом",
    "tags": [
      "house",
      "home",
      "дом"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5310029292527164639",
    "fallback": "💘",
    "label": "💘",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5310228579009699834",
    "fallback": "🎉",
    "label": "Конфетти",
    "tags": [
      "party",
      "celebrate",
      "праздник",
      "конфетти"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5377498341074542641",
    "fallback": "‼️",
    "label": "‼️",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5312315739842026755",
    "fallback": "🏆",
    "label": "Трофей",
    "tags": [
      "trophy",
      "winner",
      "трофей",
      "победитель"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5408906741125490282",
    "fallback": "🏁",
    "label": "🏁",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5368653135101310687",
    "fallback": "🎬",
    "label": "🎬",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5310045076531978942",
    "fallback": "🎵",
    "label": "Нота",
    "tags": [
      "music",
      "note",
      "музыка",
      "нота"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5420331611830886484",
    "fallback": "🔞",
    "label": "🔞",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350481781306958339",
    "fallback": "📚",
    "label": "📚",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5357107601584693888",
    "fallback": "👑",
    "label": "Корона",
    "tags": [
      "crown",
      "king",
      "queen",
      "корона",
      "король"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5375159220280762629",
    "fallback": "⚽️",
    "label": "⚽️",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5384327463629233871",
    "fallback": "🏀",
    "label": "Баскетбол",
    "tags": [
      "basketball",
      "баскетбол"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5350513667144163474",
    "fallback": "📺",
    "label": "📺",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5357121491508928442",
    "fallback": "👀",
    "label": "Глаза",
    "tags": [
      "eyes",
      "look",
      "watching",
      "глаза"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5357185426392096577",
    "fallback": "🫦",
    "label": "🫦",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5310157398516703416",
    "fallback": "🍓",
    "label": "🍓",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5310262535021142850",
    "fallback": "💄",
    "label": "💄",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5368741306484925109",
    "fallback": "👠",
    "label": "👠",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5348436127038579546",
    "fallback": "✈️",
    "label": "Самолёт",
    "tags": [
      "plane",
      "fly",
      "самолёт"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5357120306097956843",
    "fallback": "🧳",
    "label": "🧳",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5310303848311562896",
    "fallback": "🏖",
    "label": "🏖",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350424168615649565",
    "fallback": "⛅️",
    "label": "⛅️",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5413625003218313783",
    "fallback": "🦄",
    "label": "Единорог",
    "tags": [
      "unicorn",
      "единорог"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5350699789551935589",
    "fallback": "🛍",
    "label": "🛍",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5377478880577724584",
    "fallback": "👜",
    "label": "👜",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5431492767249342908",
    "fallback": "🛒",
    "label": "Корзина",
    "tags": [
      "shopping cart",
      "shop",
      "корзина"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5350497316203668441",
    "fallback": "🚂",
    "label": "🚂",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350422527938141909",
    "fallback": "🛥",
    "label": "🛥",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5418196338774907917",
    "fallback": "🏔",
    "label": "🏔",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350648297189023928",
    "fallback": "🏕",
    "label": "🏕",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5309832892262654231",
    "fallback": "🤖",
    "label": "🤖",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350751634102166060",
    "fallback": "🪩",
    "label": "🪩",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5377624166436445368",
    "fallback": "🎟",
    "label": "🎟",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5386395194029515402",
    "fallback": "🏴‍☠️",
    "label": "🏴‍☠️",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350387571199319521",
    "fallback": "🗳",
    "label": "🗳",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5357419403325481346",
    "fallback": "🎓",
    "label": "🎓",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5368585403467048206",
    "fallback": "🔭",
    "label": "🔭",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5377580546748588396",
    "fallback": "🔬",
    "label": "🔬",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5377317729109811382",
    "fallback": "🎶",
    "label": "Музыка",
    "tags": [
      "music",
      "notes",
      "музыка"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5382003830487523366",
    "fallback": "🎤",
    "label": "🎤",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5357298525765902091",
    "fallback": "🕺",
    "label": "🕺",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5357370526597653193",
    "fallback": "💃",
    "label": "💃",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5357188789351490453",
    "fallback": "🪖",
    "label": "🪖",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5348227245599105972",
    "fallback": "💼",
    "label": "💼",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5411138633765757782",
    "fallback": "🧪",
    "label": "🧪",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5386435923204382258",
    "fallback": "👨‍👩‍👧‍👦",
    "label": "👨‍👩‍👧‍👦",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5377675010259297233",
    "fallback": "👶",
    "label": "👶",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5386609083400856174",
    "fallback": "🤰",
    "label": "🤰",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5368808634392257474",
    "fallback": "💅",
    "label": "💅",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350548830041415279",
    "fallback": "🏛",
    "label": "🏛",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5355127101970194557",
    "fallback": "🧮",
    "label": "🧮",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5386379624773066504",
    "fallback": "🖨",
    "label": "🖨",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5377494501373780436",
    "fallback": "👮‍♂️",
    "label": "👮‍♂️",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350307998340226571",
    "fallback": "🩺",
    "label": "🩺",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5310094636159607472",
    "fallback": "💊",
    "label": "💊",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5310139157790596888",
    "fallback": "💉",
    "label": "💉",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5377468357907849200",
    "fallback": "🧼",
    "label": "🧼",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5418115271267197333",
    "fallback": "🪪",
    "label": "🪪",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5372819184658949787",
    "fallback": "🛃",
    "label": "🛃",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350344462612570293",
    "fallback": "🍽",
    "label": "🍽",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5384574037701696503",
    "fallback": "🐟",
    "label": "🐟",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5310039132297242441",
    "fallback": "🎨",
    "label": "🎨",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350658016700013471",
    "fallback": "🎭",
    "label": "🎭",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5357504778685392027",
    "fallback": "🎩",
    "label": "🎩",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350367161514732241",
    "fallback": "🔮",
    "label": "🔮",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350520238444126134",
    "fallback": "🍹",
    "label": "🍹",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5310132165583840589",
    "fallback": "🎂",
    "label": "Торт",
    "tags": [
      "cake",
      "birthday",
      "торт",
      "день рождения"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5350392020785437399",
    "fallback": "☕️",
    "label": "☕️",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350406176997646350",
    "fallback": "🍣",
    "label": "🍣",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350403544182694064",
    "fallback": "🍔",
    "label": "🍔",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5350444672789519765",
    "fallback": "🍕",
    "label": "Пицца",
    "tags": [
      "pizza",
      "пицца"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5312424913615723286",
    "fallback": "🦠",
    "label": "🦠",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5417915203100613993",
    "fallback": "💬",
    "label": "Чат",
    "tags": [
      "chat",
      "message",
      "чат",
      "сообщение"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5312054580060625569",
    "fallback": "🎄",
    "label": "🎄",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5309744892677727325",
    "fallback": "🎃",
    "label": "🎃",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5238156910363950406",
    "fallback": "✍️",
    "label": "✍️",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5235579393115438657",
    "fallback": "⭐️",
    "label": "⭐️",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5237699328843200968",
    "fallback": "✅",
    "label": "Галочка",
    "tags": [
      "check",
      "done",
      "ok",
      "галочка",
      "готово"
    ],
    "set": "forum_icons"
  },
  {
    "id": "5238027455754680851",
    "fallback": "🎖",
    "label": "🎖",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5238234236955148254",
    "fallback": "🤡",
    "label": "🤡",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5237889595894414384",
    "fallback": "🧠",
    "label": "🧠",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5237999392438371490",
    "fallback": "🦮",
    "label": "🦮",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5235912661102773458",
    "fallback": "🐈",
    "label": "🐈",
    "tags": [],
    "set": "forum_icons"
  },
  {
    "id": "5897792062291449826",
    "fallback": "⭐️",
    "label": "⭐️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5956159800260695086",
    "fallback": "⭐️",
    "label": "⭐️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5956098562616988692",
    "fallback": "⭐️",
    "label": "⭐️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5956571391271637639",
    "fallback": "⭐️",
    "label": "⭐️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5985305474101155474",
    "fallback": "⭐",
    "label": "Звезда",
    "tags": [
      "star",
      "звезда"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5985826831591281620",
    "fallback": "⭐",
    "label": "Звезда",
    "tags": [
      "star",
      "звезда"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5985436290215057326",
    "fallback": "⭐",
    "label": "Звезда",
    "tags": [
      "star",
      "звезда"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5967310810966398236",
    "fallback": "⭐️",
    "label": "⭐️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888993774540951956",
    "fallback": "⭐",
    "label": "Звезда",
    "tags": [
      "star",
      "звезда"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886346360994664363",
    "fallback": "🎞",
    "label": "🎞",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888578476973232531",
    "fallback": "⚡️",
    "label": "⚡️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888760051010637563",
    "fallback": "🎙",
    "label": "🎙",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888612703567613913",
    "fallback": "⏫",
    "label": "⏫",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888810705854926928",
    "fallback": "🅰",
    "label": "🅰",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886643757415140749",
    "fallback": "😜",
    "label": "😜",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888646724003566593",
    "fallback": "📄",
    "label": "📄",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886433441456591581",
    "fallback": "👋",
    "label": "👋",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886411794821419191",
    "fallback": "⭐",
    "label": "Звезда",
    "tags": [
      "star",
      "звезда"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886378723573240274",
    "fallback": "💬",
    "label": "Чат",
    "tags": [
      "chat",
      "message",
      "чат",
      "сообщение"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5889016933004612635",
    "fallback": "📢",
    "label": "Громкоговоритель",
    "tags": [
      "loudspeaker",
      "announce",
      "громкоговоритель"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886411623022728090",
    "fallback": "❇️",
    "label": "❇️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886614929594650834",
    "fallback": "❤",
    "label": "❤",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886528085355925777",
    "fallback": "📼",
    "label": "📼",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888818282177236868",
    "fallback": "🙂",
    "label": "🙂",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "6035123774725034277",
    "fallback": "🖌",
    "label": "🖌",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "6037193420680729470",
    "fallback": "📱",
    "label": "Телефон",
    "tags": [
      "phone",
      "mobile",
      "телефон"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5895293752829808957",
    "fallback": "🏷",
    "label": "🏷",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5983367464598115273",
    "fallback": "👣",
    "label": "👣",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5983353389990285649",
    "fallback": "🔒",
    "label": "Замок закрыт",
    "tags": [
      "lock",
      "secure",
      "замок"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5985762518750990451",
    "fallback": "🏪",
    "label": "🏪",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5983237610556889765",
    "fallback": "💼",
    "label": "💼",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5983273168591132353",
    "fallback": "📍",
    "label": "Метка",
    "tags": [
      "location",
      "pin",
      "метка",
      "локация"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5983192938602041487",
    "fallback": "⏰️",
    "label": "⏰️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5983569744672855025",
    "fallback": "💤",
    "label": "💤",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5985764515910784774",
    "fallback": "⬅️",
    "label": "⬅️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5778620257564366267",
    "fallback": "👋",
    "label": "👋",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5778351117733729026",
    "fallback": "🔗",
    "label": "🔗",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5778180886704954281",
    "fallback": "ℹ️",
    "label": "ℹ️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5983534401386976295",
    "fallback": "🤖",
    "label": "🤖",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5775975859085119692",
    "fallback": "💭",
    "label": "Мысль",
    "tags": [
      "thought",
      "thinking",
      "мысль"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5780715656143967291",
    "fallback": "1️⃣",
    "label": "1️⃣",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5897832125746385560",
    "fallback": "🕶",
    "label": "🕶",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5897633470624043336",
    "fallback": "🎞",
    "label": "🎞",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5897806158374113724",
    "fallback": "👁",
    "label": "👁",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5897851045077324433",
    "fallback": "⏱",
    "label": "⏱",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5895708139864462192",
    "fallback": "💽",
    "label": "💽",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5897737086710059363",
    "fallback": "📝",
    "label": "📝",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5780879616520491755",
    "fallback": "🔗",
    "label": "🔗",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5816598974030681170",
    "fallback": "📍",
    "label": "Метка",
    "tags": [
      "location",
      "pin",
      "метка",
      "локация"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5816934234882839927",
    "fallback": "⏰️",
    "label": "⏰️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5816717549487788887",
    "fallback": "⬅️",
    "label": "⬅️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5816508088227730739",
    "fallback": "👋",
    "label": "👋",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5816747545539384244",
    "fallback": "💤",
    "label": "💤",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5816903332593145525",
    "fallback": "🔗",
    "label": "🔗",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5816742056571180106",
    "fallback": "ℹ️",
    "label": "ℹ️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5816931048017105529",
    "fallback": "🤖",
    "label": "🤖",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888763542819049679",
    "fallback": "⭐",
    "label": "Звезда",
    "tags": [
      "star",
      "звезда"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886611704074211406",
    "fallback": "🎞",
    "label": "🎞",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888677360005288106",
    "fallback": "⚡️",
    "label": "⚡️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888760325888545587",
    "fallback": "🎙",
    "label": "🎙",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888587543649194044",
    "fallback": "⏫",
    "label": "⏫",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886292012478501748",
    "fallback": "🅰",
    "label": "🅰",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888499067322896420",
    "fallback": "😜",
    "label": "😜",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888814562735558615",
    "fallback": "📄",
    "label": "📄",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888720502951776376",
    "fallback": "💤",
    "label": "💤",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888945799756255627",
    "fallback": "⭐",
    "label": "Звезда",
    "tags": [
      "star",
      "звезда"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5931793690581275367",
    "fallback": "💬",
    "label": "Чат",
    "tags": [
      "chat",
      "message",
      "чат",
      "сообщение"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886367294665265093",
    "fallback": "📢",
    "label": "Громкоговоритель",
    "tags": [
      "loudspeaker",
      "announce",
      "громкоговоритель"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888854085024616252",
    "fallback": "❇️",
    "label": "❇️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886506464490558169",
    "fallback": "❤",
    "label": "❤",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886446274818871876",
    "fallback": "📼",
    "label": "📼",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5888981220351545352",
    "fallback": "🙂",
    "label": "🙂",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "6037389275484393943",
    "fallback": "🖌",
    "label": "🖌",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "6037232942969786590",
    "fallback": "📱",
    "label": "Телефон",
    "tags": [
      "phone",
      "mobile",
      "телефон"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5886208883386487240",
    "fallback": "🏷",
    "label": "🏷",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5933769822214034093",
    "fallback": "💬",
    "label": "Чат",
    "tags": [
      "chat",
      "message",
      "чат",
      "сообщение"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5934050846219179011",
    "fallback": "👣",
    "label": "👣",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5985830207435578612",
    "fallback": "🏪",
    "label": "🏪",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5985293048760766504",
    "fallback": "💬",
    "label": "Чат",
    "tags": [
      "chat",
      "message",
      "чат",
      "сообщение"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5985684264446857232",
    "fallback": "📍",
    "label": "Метка",
    "tags": [
      "location",
      "pin",
      "метка",
      "локация"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5985813388343644502",
    "fallback": "👋",
    "label": "👋",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5985346271995498377",
    "fallback": "💤",
    "label": "💤",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5985330346256765863",
    "fallback": "⏰️",
    "label": "⏰️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5983263358885827952",
    "fallback": "🤖",
    "label": "🤖",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5983121629260026062",
    "fallback": "💼",
    "label": "💼",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5985742598692672806",
    "fallback": "📷",
    "label": "Камера",
    "tags": [
      "camera",
      "photo",
      "камера",
      "фото"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5778315916181772492",
    "fallback": "ℹ️",
    "label": "ℹ️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5778497777981986004",
    "fallback": "🔗",
    "label": "🔗",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5963196923786563421",
    "fallback": "🥇",
    "label": "Золотая медаль",
    "tags": [
      "gold medal",
      "first place",
      "золото"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5960929739400023700",
    "fallback": "👁",
    "label": "👁",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5890755071909565319",
    "fallback": "🎞",
    "label": "🎞",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5960784595275222721",
    "fallback": "👁",
    "label": "👁",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5960943526245043803",
    "fallback": "⏲️",
    "label": "⏲️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5960603218806312857",
    "fallback": "🖼",
    "label": "🖼",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5963114426054742389",
    "fallback": "📝",
    "label": "📝",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5960708131972452237",
    "fallback": "🔗",
    "label": "🔗",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5778356881579840072",
    "fallback": "🗺",
    "label": "🗺",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5778420863707649338",
    "fallback": "⏰️",
    "label": "⏰️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5778594273012224761",
    "fallback": "💬",
    "label": "Чат",
    "tags": [
      "chat",
      "message",
      "чат",
      "сообщение"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5778475989612893187",
    "fallback": "👋",
    "label": "👋",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5778489145097721084",
    "fallback": "⛱️",
    "label": "⛱️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5778585300825543755",
    "fallback": "🔗",
    "label": "🔗",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5778298959650887343",
    "fallback": "ℹ️",
    "label": "ℹ️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5778296180807046576",
    "fallback": "🤖",
    "label": "🤖",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5938420017665152105",
    "fallback": "⭐️",
    "label": "⭐️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5940706490749817001",
    "fallback": "⭐",
    "label": "Звезда",
    "tags": [
      "star",
      "звезда"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5938274774756103272",
    "fallback": "🏪",
    "label": "🏪",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5938540495792771769",
    "fallback": "🎁",
    "label": "Подарок",
    "tags": [
      "gift",
      "present",
      "подарок"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5904471488056005364",
    "fallback": "🆕",
    "label": "🆕",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5904241552686846375",
    "fallback": "🆕",
    "label": "🆕",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5996699030199997602",
    "fallback": "🪙",
    "label": "🪙",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5787537876686213037",
    "fallback": "⚡",
    "label": "Молния",
    "tags": [
      "lightning",
      "electric",
      "молния",
      "электричество"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5787297856733844050",
    "fallback": "⚡",
    "label": "Молния",
    "tags": [
      "lightning",
      "electric",
      "молния",
      "электричество"
    ],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5952052974007095673",
    "fallback": "⭐️",
    "label": "⭐️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5951802070607597636",
    "fallback": "⭐️",
    "label": "⭐️",
    "tags": [],
    "set": "TgPremiumIcon"
  },
  {
    "id": "5794005105296545593",
    "fallback": "💭",
    "label": "Мысль",
    "tags": [
      "thought",
      "thinking",
      "мысль"
    ],
    "set": "TgPremiumIcon"
  }
];
