// Данные premium emoji.
// ID заполняются скриптом: node scripts/fetch-premium-emoji.mjs <BOT_TOKEN>
// Без ID — вставляется Unicode-символ. С ID — вставляется <tg-emoji> тег.

export interface PremiumEmojiEntry {
  id: string;        // custom_emoji_id (пустой до запуска скрипта)
  fallback: string;  // Unicode emoji символ
  label: string;     // Русское название
  tags: string[];    // Теги для поиска (рус + eng)
  set: string;       // Название пака
}

export const PREMIUM_EMOJI_DATA: PremiumEmojiEntry[] = [
  // ── Лица и эмоции ────────────────────────────────────────────────────────
  { id: '', fallback: '😀', label: 'Улыбка',            tags: ['улыбка','smile','happy'],                     set: '' },
  { id: '', fallback: '😂', label: 'Смех',              tags: ['смех','laugh','lol','хаха'],                  set: '' },
  { id: '', fallback: '😍', label: 'Влюблённость',      tags: ['влюблённость','love','heart eyes'],           set: '' },
  { id: '', fallback: '🥰', label: 'Любовь',            tags: ['любовь','love','hearts'],                     set: '' },
  { id: '', fallback: '😎', label: 'Крутой',            tags: ['крутой','cool','sunglasses'],                 set: '' },
  { id: '', fallback: '🤩', label: 'Восторг',           tags: ['восторг','excited','star struck'],            set: '' },
  { id: '', fallback: '🥳', label: 'Праздник',          tags: ['праздник','party','celebrate'],               set: '' },
  { id: '', fallback: '😏', label: 'Ухмылка',           tags: ['ухмылка','smirk'],                            set: '' },
  { id: '', fallback: '🤔', label: 'Думает',            tags: ['думает','think','hmm'],                       set: '' },
  { id: '', fallback: '😤', label: 'Злость',            tags: ['злость','angry','frustrated'],                set: '' },
  { id: '', fallback: '😈', label: 'Чертёнок',          tags: ['чертёнок','devil','evil'],                    set: '' },
  { id: '', fallback: '🤯', label: 'Взрыв мозга',       tags: ['шок','mind blown','shocked'],                 set: '' },
  { id: '', fallback: '😭', label: 'Плач',              tags: ['плач','cry','sad','слёзы'],                   set: '' },
  { id: '', fallback: '🥺', label: 'Пожалуйста',        tags: ['пожалуйста','pleading','cute'],               set: '' },
  { id: '', fallback: '😴', label: 'Сон',               tags: ['сон','sleep','tired'],                        set: '' },
  { id: '', fallback: '🤑', label: 'Деньги',            tags: ['деньги','money','rich'],                      set: '' },
  { id: '', fallback: '🥶', label: 'Холод',             tags: ['холод','cold','freezing'],                    set: '' },
  { id: '', fallback: '🥵', label: 'Жара',              tags: ['жара','hot','sweating'],                      set: '' },
  { id: '', fallback: '🤫', label: 'Тихо',              tags: ['тихо','shush','secret','секрет'],             set: '' },
  { id: '', fallback: '🤭', label: 'Хихикает',          tags: ['хихикает','giggle','oops'],                   set: '' },
  // ── Жесты ────────────────────────────────────────────────────────────────
  { id: '', fallback: '👍', label: 'Лайк',              tags: ['лайк','like','thumbs up','одобрение'],        set: '' },
  { id: '', fallback: '👎', label: 'Дизлайк',           tags: ['дизлайк','dislike','thumbs down'],            set: '' },
  { id: '', fallback: '👏', label: 'Аплодисменты',      tags: ['аплодисменты','clap','applause'],             set: '' },
  { id: '', fallback: '🙌', label: 'Ура',               tags: ['ура','celebrate','hooray'],                   set: '' },
  { id: '', fallback: '🤝', label: 'Рукопожатие',       tags: ['рукопожатие','handshake','deal'],             set: '' },
  { id: '', fallback: '✌️', label: 'Победа',            tags: ['победа','peace','victory'],                   set: '' },
  { id: '', fallback: '🤞', label: 'Удача',             tags: ['удача','luck','fingers crossed'],             set: '' },
  { id: '', fallback: '💪', label: 'Сила',              tags: ['сила','strong','muscle','мышца'],             set: '' },
  { id: '', fallback: '🙏', label: 'Спасибо',           tags: ['спасибо','thank you','pray','просьба'],       set: '' },
  { id: '', fallback: '👀', label: 'Глаза',             tags: ['глаза','eyes','look','watching'],             set: '' },
  { id: '', fallback: '💋', label: 'Поцелуй',           tags: ['поцелуй','kiss','lips'],                      set: '' },
  // ── Сердца ───────────────────────────────────────────────────────────────
  { id: '', fallback: '❤️', label: 'Красное сердце',    tags: ['сердце','heart','love','red','любовь'],       set: '' },
  { id: '', fallback: '🧡', label: 'Оранжевое сердце',  tags: ['сердце','heart','orange'],                    set: '' },
  { id: '', fallback: '💛', label: 'Жёлтое сердце',     tags: ['сердце','heart','yellow'],                    set: '' },
  { id: '', fallback: '💚', label: 'Зелёное сердце',    tags: ['сердце','heart','green'],                     set: '' },
  { id: '', fallback: '💙', label: 'Синее сердце',      tags: ['сердце','heart','blue'],                      set: '' },
  { id: '', fallback: '💜', label: 'Фиолетовое сердце', tags: ['сердце','heart','purple'],                    set: '' },
  { id: '', fallback: '🖤', label: 'Чёрное сердце',     tags: ['сердце','heart','black'],                     set: '' },
  { id: '', fallback: '🤍', label: 'Белое сердце',      tags: ['сердце','heart','white'],                     set: '' },
  { id: '', fallback: '💔', label: 'Разбитое сердце',   tags: ['разбитое сердце','broken heart'],             set: '' },
  { id: '', fallback: '💕', label: 'Два сердца',        tags: ['два сердца','two hearts'],                    set: '' },
  { id: '', fallback: '💯', label: '100%',              tags: ['100','perfect','идеально'],                   set: '' },
  // ── Природа и стихии ─────────────────────────────────────────────────────
  { id: '', fallback: '🔥', label: 'Огонь',             tags: ['огонь','fire','flame','hot','пламя'],         set: '' },
  { id: '', fallback: '⚡', label: 'Молния',            tags: ['молния','lightning','electric'],              set: '' },
  { id: '', fallback: '✨', label: 'Искры',             tags: ['искры','sparkles','glitter','блёстки'],       set: '' },
  { id: '', fallback: '💫', label: 'Вспышка',           tags: ['вспышка','dizzy','flash'],                    set: '' },
  { id: '', fallback: '⭐', label: 'Звезда',            tags: ['звезда','star'],                              set: '' },
  { id: '', fallback: '🌟', label: 'Светящаяся звезда', tags: ['звезда','star','glowing'],                    set: '' },
  { id: '', fallback: '🌈', label: 'Радуга',            tags: ['радуга','rainbow'],                           set: '' },
  { id: '', fallback: '☀️', label: 'Солнце',            tags: ['солнце','sun','sunny'],                       set: '' },
  { id: '', fallback: '🌙', label: 'Луна',              tags: ['луна','moon','night','ночь'],                 set: '' },
  { id: '', fallback: '❄️', label: 'Снежинка',          tags: ['снежинка','snowflake','cold','холод'],        set: '' },
  { id: '', fallback: '🌊', label: 'Волна',             tags: ['волна','wave','ocean','море'],                set: '' },
  { id: '', fallback: '🌺', label: 'Цветок',            tags: ['цветок','flower','hibiscus'],                 set: '' },
  { id: '', fallback: '🌹', label: 'Роза',              tags: ['роза','rose'],                                set: '' },
  { id: '', fallback: '🍀', label: 'Клевер',            tags: ['клевер','clover','lucky','удача'],            set: '' },
  { id: '', fallback: '🦋', label: 'Бабочка',           tags: ['бабочка','butterfly'],                        set: '' },
  { id: '', fallback: '🦄', label: 'Единорог',          tags: ['единорог','unicorn'],                         set: '' },
  { id: '', fallback: '🐉', label: 'Дракон',            tags: ['дракон','dragon'],                            set: '' },
  // ── Награды и достижения ─────────────────────────────────────────────────
  { id: '', fallback: '💎', label: 'Алмаз',             tags: ['алмаз','бриллиант','diamond','gem'],          set: '' },
  { id: '', fallback: '👑', label: 'Корона',            tags: ['корона','crown','king','queen','король'],      set: '' },
  { id: '', fallback: '🏆', label: 'Трофей',            tags: ['трофей','trophy','winner','победитель'],      set: '' },
  { id: '', fallback: '🥇', label: 'Золото',            tags: ['золото','gold','first','первое место'],       set: '' },
  { id: '', fallback: '🎯', label: 'Цель',              tags: ['цель','target','bullseye'],                   set: '' },
  { id: '', fallback: '🚀', label: 'Ракета',            tags: ['ракета','rocket','launch','запуск'],          set: '' },
  { id: '', fallback: '🎁', label: 'Подарок',           tags: ['подарок','gift','present'],                   set: '' },
  { id: '', fallback: '🎉', label: 'Конфетти',          tags: ['конфетти','party','celebrate','праздник'],    set: '' },
  { id: '', fallback: '🎊', label: 'Хлопушка',          tags: ['хлопушка','confetti','party'],                set: '' },
  { id: '', fallback: '🏅', label: 'Медаль',            tags: ['медаль','medal','award'],                     set: '' },
  // ── Бизнес и финансы ─────────────────────────────────────────────────────
  { id: '', fallback: '💰', label: 'Деньги',            tags: ['деньги','money','cash','bag'],                set: '' },
  { id: '', fallback: '💳', label: 'Карта',             tags: ['карта','card','credit','оплата'],             set: '' },
  { id: '', fallback: '📈', label: 'Рост',              tags: ['рост','growth','chart','up'],                 set: '' },
  { id: '', fallback: '📉', label: 'Падение',           tags: ['падение','decline','chart','down'],           set: '' },
  { id: '', fallback: '📊', label: 'Статистика',        tags: ['статистика','stats','chart','график'],        set: '' },
  { id: '', fallback: '🛒', label: 'Корзина',           tags: ['корзина','cart','shop','покупка'],            set: '' },
  // ── UI и статусы ─────────────────────────────────────────────────────────
  { id: '', fallback: '✅', label: 'Готово',            tags: ['готово','check','done','ok','галочка'],       set: '' },
  { id: '', fallback: '❌', label: 'Нет',               tags: ['нет','no','error','крест','ошибка'],          set: '' },
  { id: '', fallback: '⚠️', label: 'Предупреждение',    tags: ['предупреждение','warning','alert'],           set: '' },
  { id: '', fallback: '🚫', label: 'Запрет',            tags: ['запрет','ban','prohibited','нет'],            set: '' },
  { id: '', fallback: '❓', label: 'Вопрос',            tags: ['вопрос','question'],                          set: '' },
  { id: '', fallback: '❗', label: 'Важно',             tags: ['важно','important','exclamation'],            set: '' },
  { id: '', fallback: '💡', label: 'Идея',              tags: ['идея','idea','lamp','лампочка'],              set: '' },
  { id: '', fallback: '📌', label: 'Закреп',            tags: ['закреп','pin','pushpin'],                     set: '' },
  { id: '', fallback: '🔔', label: 'Уведомление',       tags: ['уведомление','bell','notification'],          set: '' },
  { id: '', fallback: '🔕', label: 'Без звука',         tags: ['без звука','mute','silent'],                  set: '' },
  { id: '', fallback: '💬', label: 'Чат',               tags: ['чат','chat','message','сообщение'],           set: '' },
  { id: '', fallback: '📢', label: 'Анонс',             tags: ['анонс','announce','speaker','мегафон'],       set: '' },
  { id: '', fallback: '🔑', label: 'Ключ',              tags: ['ключ','key','access'],                        set: '' },
  { id: '', fallback: '🔒', label: 'Закрыто',           tags: ['закрыто','locked','secure','замок'],          set: '' },
  { id: '', fallback: '🔓', label: 'Открыто',           tags: ['открыто','unlocked','open'],                  set: '' },
  { id: '', fallback: '⚙️', label: 'Настройки',         tags: ['настройки','settings','gear','шестерёнка'],  set: '' },
  { id: '', fallback: '🛡️', label: 'Защита',            tags: ['защита','shield','security'],                 set: '' },
  { id: '', fallback: '🌍', label: 'Земля',             tags: ['земля','world','globe','мир'],                set: '' },
  { id: '', fallback: '📍', label: 'Локация',           tags: ['локация','location','pin','место'],           set: '' },
  // ── Технологии ───────────────────────────────────────────────────────────
  { id: '', fallback: '📱', label: 'Телефон',           tags: ['телефон','phone','mobile'],                   set: '' },
  { id: '', fallback: '💻', label: 'Ноутбук',           tags: ['ноутбук','laptop','computer'],                set: '' },
  { id: '', fallback: '📷', label: 'Камера',            tags: ['камера','camera','photo','фото'],             set: '' },
  { id: '', fallback: '🎥', label: 'Видео',             tags: ['видео','video','camera'],                     set: '' },
  { id: '', fallback: '🎵', label: 'Музыка',            tags: ['музыка','music','note','нота'],               set: '' },
  { id: '', fallback: '🎮', label: 'Игры',              tags: ['игры','game','gaming','геймплей'],            set: '' },
];
