import type {
  MediaGroupItemType,
  MediaSourceMode,
  PollType,
  RequestMethodConfig,
  RequestParseMode,
} from '../types/requestBuilder';

export const DEFAULT_CHAT_ID = '{{ telegram_id}}';

export const REQUEST_METHODS: RequestMethodConfig[] = [
  // ── ТЕКСТ ────────────────────────────────────────────────────────────────
  {
    id: 'sendMessage',
    title: 'sendMessage',
    description: 'Текстовое сообщение',
    category: 'text',
    supportsParseMode: true,
    supportsDirectMessagesTopic: true,
    supportsInlineKeyboard: true,
    note: 'Подходит для обычного текста, HTML и MarkdownV2.',
  },
  // ── МЕДИА ────────────────────────────────────────────────────────────────
  {
    id: 'sendPhoto',
    title: 'sendPhoto',
    description: 'Фото',
    category: 'media',
    mediaField: 'photo',
    supportsCaption: true,
    supportsParseMode: true,
    supportsSpoiler: true,
    supportsShowCaptionAboveMedia: true,
    supportsDirectMessagesTopic: true,
    supportsInlineKeyboard: true,
  },
  {
    id: 'sendVideo',
    title: 'sendVideo',
    description: 'Видео',
    category: 'media',
    mediaField: 'video',
    supportsCaption: true,
    supportsParseMode: true,
    supportsSpoiler: true,
    supportsShowCaptionAboveMedia: true,
    supportsDirectMessagesTopic: true,
    supportsInlineKeyboard: true,
  },
  {
    id: 'sendAnimation',
    title: 'sendAnimation',
    description: 'GIF / анимация',
    category: 'media',
    mediaField: 'animation',
    supportsCaption: true,
    supportsParseMode: true,
    supportsShowCaptionAboveMedia: true,
    supportsDirectMessagesTopic: true,
    supportsInlineKeyboard: true,
  },
  {
    id: 'sendAudio',
    title: 'sendAudio',
    description: 'Музыка / аудио',
    category: 'media',
    mediaField: 'audio',
    supportsCaption: true,
    supportsParseMode: true,
    supportsDirectMessagesTopic: true,
    supportsInlineKeyboard: true,
  },
  {
    id: 'sendDocument',
    title: 'sendDocument',
    description: 'Документ',
    category: 'media',
    mediaField: 'document',
    supportsCaption: true,
    supportsParseMode: true,
    supportsDirectMessagesTopic: true,
    supportsInlineKeyboard: true,
  },
  {
    id: 'sendSticker',
    title: 'sendSticker',
    description: 'Стикер',
    category: 'media',
    mediaField: 'sticker',
    supportsDirectMessagesTopic: true,
    supportsInlineKeyboard: true,
    note: 'HTTP URL подходит только для статических WEBP-стикеров.',
  },
  {
    id: 'sendVoice',
    title: 'sendVoice',
    description: 'Голосовое',
    category: 'media',
    mediaField: 'voice',
    supportsCaption: true,
    supportsParseMode: true,
    supportsDirectMessagesTopic: true,
    supportsInlineKeyboard: true,
  },
  {
    id: 'sendVideoNote',
    title: 'sendVideoNote',
    description: 'Видеосообщение',
    category: 'media',
    mediaField: 'video_note',
    supportsDirectMessagesTopic: true,
    supportsInlineKeyboard: true,
  },
  {
    id: 'sendMediaGroup',
    title: 'sendMediaGroup',
    description: 'Альбом media group',
    category: 'album',
    supportsParseMode: true,
    supportsDirectMessagesTopic: true,
    note: 'Можно смешивать фото и видео. Документы и аудио нужно отправлять отдельным альбомом одного типа.',
  },
  // ── ГЕОЛОКАЦИЯ / МЕСТО / КОНТАКТ ─────────────────────────────────────────
  {
    id: 'sendLocation',
    title: 'sendLocation',
    description: 'Геолокация',
    category: 'location',
    supportsDirectMessagesTopic: true,
    supportsInlineKeyboard: true,
  },
  {
    id: 'sendVenue',
    title: 'sendVenue',
    description: 'Место / venue',
    category: 'venue',
    supportsDirectMessagesTopic: true,
    supportsInlineKeyboard: true,
  },
  {
    id: 'sendContact',
    title: 'sendContact',
    description: 'Контакт',
    category: 'contact',
    supportsDirectMessagesTopic: true,
    supportsInlineKeyboard: true,
  },
  // ── ИНТЕРАКТИВ ───────────────────────────────────────────────────────────
  {
    id: 'sendPoll',
    title: 'sendPoll',
    description: 'Опрос',
    category: 'poll',
    supportsInlineKeyboard: true,
    note: 'Для опроса нужно минимум 2 варианта ответа.',
  },
  {
    id: 'sendDice',
    title: 'sendDice',
    description: 'Dice / emoji game',
    category: 'dice',
    supportsDirectMessagesTopic: true,
    supportsInlineKeyboard: true,
  },
  // ── ПОЛУЧЕНИЕ ДАННЫХ ─────────────────────────────────────────────────────
  {
    id: 'getMe',
    title: 'getMe',
    description: 'Информация о боте',
    category: 'get',
    hint: 'Не требует параметров. Возвращает объект User с данными бота.',
  },
  {
    id: 'getChat',
    title: 'getChat',
    description: 'Информация о чате',
    category: 'get',
    hint: 'Возвращает актуальную информацию о чате, группе или канале.',
  },
  {
    id: 'getChatMember',
    title: 'getChatMember',
    description: 'Участник чата',
    category: 'get',
    hint: 'Статус пользователя в чате: member, administrator, kicked и т.д.',
  },
  {
    id: 'getChatAdministrators',
    title: 'getChatAdministrators',
    description: 'Список администраторов',
    category: 'get',
    hint: 'Возвращает массив ChatMember со всеми администраторами чата.',
  },
  {
    id: 'getChatMemberCount',
    title: 'getChatMemberCount',
    description: 'Число участников',
    category: 'get',
    hint: 'Возвращает целое число — количество участников чата.',
  },
  {
    id: 'getFile',
    title: 'getFile',
    description: 'Информация о файле',
    category: 'get',
    hint: 'Возвращает объект File с file_path для скачивания через Bot API.',
  },
  {
    id: 'getUserProfilePhotos',
    title: 'getUserProfilePhotos',
    description: 'Фото профиля',
    category: 'get',
    hint: 'Возвращает список фотографий профиля пользователя.',
  },
  // ── АДМИНИСТРИРОВАНИЕ ────────────────────────────────────────────────────
  {
    id: 'banChatMember',
    title: 'banChatMember',
    description: 'Заблокировать участника',
    category: 'admin',
    hint: 'Блокирует пользователя в группе/супергруппе/канале.',
  },
  {
    id: 'unbanChatMember',
    title: 'unbanChatMember',
    description: 'Разблокировать участника',
    category: 'admin',
    hint: 'Снимает бан. only_if_banned = не кикать, если ещё в чате.',
  },
  {
    id: 'restrictChatMember',
    title: 'restrictChatMember',
    description: 'Ограничить права участника',
    category: 'admin',
    hint: 'Управляет permissions отдельного пользователя в супергруппе.',
  },
  {
    id: 'pinChatMessage',
    title: 'pinChatMessage',
    description: 'Закрепить сообщение',
    category: 'admin',
    hint: 'Закрепляет сообщение в чате. Бот должен быть администратором.',
  },
  {
    id: 'unpinChatMessage',
    title: 'unpinChatMessage',
    description: 'Открепить сообщение',
    category: 'admin',
    hint: 'Без message_id открепляет последнее закреплённое сообщение.',
  },
  {
    id: 'unpinAllChatMessages',
    title: 'unpinAllChatMessages',
    description: 'Открепить все сообщения',
    category: 'admin',
    hint: 'Удаляет все закреплённые сообщения в чате.',
  },
  {
    id: 'setMyCommands',
    title: 'setMyCommands',
    description: 'Установить команды бота',
    category: 'admin',
    hint: 'Задаёт список команд для меню бота. Видны при вводе /.',
  },
  {
    id: 'deleteMyCommands',
    title: 'deleteMyCommands',
    description: 'Удалить команды бота',
    category: 'admin',
    hint: 'Сбрасывает список команд бота для указанного языка.',
  },
  // ── WEBHOOK / UPDATES ────────────────────────────────────────────────────
  {
    id: 'setWebhook',
    title: 'setWebhook',
    description: 'Установить webhook',
    category: 'webhook',
    hint: 'Telegram будет отправлять обновления POST-запросами на ваш URL.',
  },
  {
    id: 'deleteWebhook',
    title: 'deleteWebhook',
    description: 'Удалить webhook',
    category: 'webhook',
    hint: 'После удаления webhook можно использовать getUpdates.',
  },
  {
    id: 'getWebhookInfo',
    title: 'getWebhookInfo',
    description: 'Информация о webhook',
    category: 'webhook',
    hint: 'Не требует параметров. Возвращает текущий WebhookInfo.',
  },
  {
    id: 'getUpdates',
    title: 'getUpdates',
    description: 'Получить обновления (polling)',
    category: 'webhook',
    hint: 'Long-polling: задайте timeout > 0, чтобы держать соединение открытым.',
  },
  // ── INLINE РЕЖИМ ─────────────────────────────────────────────────────────
  {
    id: 'answerInlineQuery',
    title: 'answerInlineQuery',
    description: 'Ответ на inline-запрос',
    category: 'inline',
    hint: 'Отправляет результаты в ответ на InlineQuery. В конструкторе — один article.',
  },
  {
    id: 'answerWebAppQuery',
    title: 'answerWebAppQuery',
    description: 'Ответ на Web App запрос',
    category: 'inline',
    hint: 'Отправляет результат в ответ на WebAppQuery из Telegram Mini App.',
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  text: 'Текст',
  media: 'Медиа',
  album: 'Альбом',
  location: 'Геолокация',
  venue: 'Место',
  contact: 'Контакт',
  poll: 'Опрос',
  dice: 'Dice',
  get: 'Получение данных',
  admin: 'Администрирование',
  webhook: 'Webhook / Updates',
  inline: 'Inline режим',
};

export const MEDIA_SOURCE_OPTIONS: Array<{ value: MediaSourceMode; label: string }> = [
  { value: 'file_id', label: 'file_id' },
  { value: 'url', label: 'HTTP URL' },
];

export const PARSE_MODE_OPTIONS: Array<{ value: RequestParseMode; label: string }> = [
  { value: '', label: 'Без parse_mode' },
  { value: 'HTML', label: 'HTML' },
  { value: 'Markdown', label: 'Markdown' },
  { value: 'MarkdownV2', label: 'MarkdownV2' },
];

export const MESSAGE_EFFECT_OPTIONS = [
  { value: '5107584321108051014', label: '👍 Лайк' },
  { value: '5104858069142078462', label: '👎 Дизлайк' },
  { value: '5159385139981059251', label: '❤️ Сердце' },
  { value: '5104841245755180586', label: '🔥 Огонь' },
  { value: '5046509860389126442', label: '🎉 Праздник' },
  { value: '5046589136895476101', label: '💩 Мем' },
  { value: '5170169077011841524', label: '🥰 Влюбленность' },
  { value: '5170166362592510656', label: '👏 Аплодисменты' },
  { value: '5048771083361059460', label: '😁 Улыбка' },
  { value: '5170257231215591956', label: '🤔 Размышление' },
  { value: '5158936234294248618', label: '🤯 Взрыв мозга' },
  { value: '4967494041374556629', label: '😱 Шок' },
  { value: '5170149264327704981', label: '🤬 Ярость' },
  { value: '5046551865169281494', label: '😢 Слезы' },
  { value: '5161554034041029689', label: '🤩 Восторг' },
  { value: '5125503964049048317', label: '🤮 Фу' },
  { value: '5066712811023894584', label: '🙏 Благодарность' },
  { value: '5066947642655769508', label: '👌 Ок' },
  { value: '5095856784057303751', label: '🕊 Голубь' },
  { value: '4988252812317033130', label: '🤡 Клоун' },
  { value: '4988134357119009237', label: '🥱 Зевок' },
  { value: '4927250902185673331', label: '🥴 Шатает' },
  { value: '5066779159678682060', label: '😍 Восхищение' },
  { value: '5075655057488217321', label: '🐳 Кит' },
  { value: '5066576334143095943', label: '❤️‍🔥 Пылающее сердце' },
  { value: '4961155507164283482', label: '🌚 Луна' },
  { value: '4961017943656759969', label: '🌭 Хот-дог' },
  { value: '4962976753686414048', label: '💯 Сто' },
  { value: '5066993302453093673', label: '🤣 Смех' },
  { value: '5123236135417415011', label: '⚡ Молния' },
  { value: '5123233223429587601', label: '🍌 Банан' },
  { value: '5123046001510188023', label: '🏆 Кубок' },
  { value: '5123265598893064880', label: '💔 Разбитое сердце' },
  { value: '5122846324185629167', label: '🤨 Скепсис' },
  { value: '5066978240002786236', label: '😐 Без эмоций' },
  { value: '4961016393173566021', label: '🍓 Клубника' },
  { value: '4913460264709391187', label: '✍ Пишет' },
  { value: '4989997728680380153', label: '☃ Снеговик' },
  { value: '5071394291016795490', label: '☝ Указатель' },
  { value: '5087137729863484424', label: '✅ Подтверждение' },
  { value: '5067074180982244082', label: '✌ Победа' },
  { value: '5089460564141278042', label: '✨ Искры' },
  { value: '5066795381770158548', label: '❄ Снежинка' },
] as const;

export const ALBUM_ITEM_TYPE_OPTIONS: Array<{ value: MediaGroupItemType; label: string }> = [
  { value: 'photo', label: 'Фото' },
  { value: 'video', label: 'Видео' },
  { value: 'document', label: 'Документ' },
  { value: 'audio', label: 'Аудио' },
];

export const POLL_TYPE_OPTIONS: Array<{ value: PollType; label: string }> = [
  { value: 'regular', label: 'Обычный' },
  { value: 'quiz', label: 'Quiz' },
];

export const DICE_EMOJI_OPTIONS = [
  { value: '🎲', label: '🎲' },
  { value: '🎯', label: '🎯' },
  { value: '🏀', label: '🏀' },
  { value: '⚽', label: '⚽' },
  { value: '🎳', label: '🎳' },
  { value: '🎰', label: '🎰' },
] as const;
